name: Artifacts
on:
  push:
    branch:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: src
    outputs:
      js-filename: ${{ steps.build.outputs.js-filename }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: js_file=$(basename dist/assets/*.js) echo "js_filename=$js_file" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: src/dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output files
        run: ls
      - name: Output filename
        run: echo ${{ needs.build.outputs.js-filename }}
