name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check github context
        run: echo "${{ toJSON(github) }}"
      - name: Add label to issue
        run: gh issue edit "${{ github.event.issue.number }}" --repo ${{ github.repository }} --add-label "new issue"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
