name: New Issue

on:
  issues:
    types: [opened]

jobs:
  show-issue-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show issue information
        run: |
          echo "Issue title: $ISSUE_TITLE"
          echo "Issue body: $ISSUE_BODY"
          echo "Issue user: $ISSUE_USER"
          echo "Issue number: $ISSUE_NUMBER"
          echo "Number of issues currently open: $(gh issue list --state open --limit 1 | wc -l)"
      - name: Add tag to issue
        run: gh issue edit $ISSUE_NUMBER --add-label "new-issue"
