name: Variables & Secrets
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  echo-variables:
    environment:
      name: production
    env:
      GREETING_TEXT: "Pipeline defined variable"
    runs-on: ubuntu-latest
    steps:
      - name: Show environment secret
        run: echo "${{ secrets.TEST_SECRET }}"
      - name: Show environment variable
        run: echo "${{ vars.TEST_VARIABLE }}"
      - name: Show pipeline variable
        run: echo $GREETING_TEXT
