name: Variables & Secrets
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  echo-variables:
    environment: production
    env:
      GREETING_TEXT: "Hello pipelines"
    runs-on: ubuntu-latest
    steps:
      - name: Show envs
        run: echo "${{ toJSON(env) }}"
      - name: Show secret
        run: echo "${{ secrets.TEST_SECRET }}"
      - name: Show variable
        run: echo "${{ env.TEST_VARIABLE }}"
      - name: Show alternative syntax
        run: echo $GREETING_TEXT
