name: Variables & Secrets
on:
  push:
    branches:
      - main
  workflow_dispatch:
environment: production
jobs:
  env:
    GREETING_TEXT: "Hello pipelines"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Show context
        run: echo "${{ toJSON(github) }}"
      - name: Show secret
        run: echo "${{ secrets.TEST_SECRET }}"
      - name: Show variable
        run: echo "${{ env.TEST_VARIABLE }}"
      - name: Show alternative syntax
        run: echo $GREETING_TEXT
